app/models.py
from . import db
class Role(db.Model):
    """docstring for Role"""

    __tablename__ = 'roles'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String,unique=True,index=True)
    users = db.relationship('User',backref='role')
    def __repr__(self):
        return "<Role %s>" % self.name

class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String,unique=True,index=True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    def __repr__(self):
        return "<User %s>" % self.username

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField,SubmitField
from wtforms.validators import *

class NameForm(Form):
    name = StringField("input your name",validators=[DataRequired()])
    submit = SubmitField("Submit")

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from config import *
from flask.ext.triangle import Triangle


bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
# migrate = Migrate(app,db)
# manager.add_command("db",MigrateCommand)
triangle = Triangle()
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    triangle.init_app(app)
    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    return app


# import ipdb;ipdb.set_trace()

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__,template_folder='main.templates',static_folder='main.static')
from . import views,errors

app/main/views.py
import datetime

from flask import request,render_template, session, redirect,url_for,flash
from . import main
from .forms import *
from ..models import *
from .. import db

@main.route('/',methods=["POST","GET"])
def home():
    return render_template('index.html',current_time=datetime.datetime.now())



@main.route('/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post %d' % post_id


@main.route('/user',methods=["POST","GET"])
def user():
    form = NameForm()
    if request.method=='POST':
        if form.validate():
            session['name'] = form.name.data
            # form.name.data = ''
            return redirect(url_for('/',current_time=datetime.datetime.now()))
        else:
            flash("this field is blank")

    # if request.method == "POST":
    # 	session['user'] = request.form['username']
    return render_template('user.html',form=form)


@main.route('/test',methods=['POST','GET'])
def test():
    return render_template('test.html')


@main.route('/todo',methods=['POST','GET'])
def todo():
    return render_template('todo.html')

app/templates/base.html
<!DOCTYPE html>
{%  block html %}
<html>
{% endblock %}
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>

{% block stylesheet %}

<link rel= "stylesheet" href= "{{ url_for('static', filename = 'bower_components/bootstrap/dist/css/bootstrap.min.css') }}" >
<link rel= "stylesheet" href= "{{ url_for('static', filename = 'bower_components/bootstrap/dist/css/bootstrap-theme.css') }}">
<link rel= "stylesheet" href= "{{ url_for('static', filename = 'bower_components/angular/angular-csp.css') }}" >
<script src="{{ url_for('static', filename = 'bower_components/angular/angular.min.js') }}"></script>

{% endblock %}

{% block script_top %}
{% endblock %}
</head>

{% block body %}
<body>
{%  endblock %}

    {% block header %}
        <div class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" type="button" data="collapse"
			data-target="navbar-collapse">
				<span class="sr-only">Toggle</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>

			</button>
			<a class="navbar-brand" href="/">Flask</a>

		</div>
		<div class="navbar-collapse collapse">
			<ul class="navbar-nav nav">
				<li><a href="/">Home</a></li>
			</ul>
		</div>
	</div>
    </div>
    {% endblock %}

    {% block content %}
    <div class="container">

        {% for message in get_flashed_messages() %}
        <div class= "alert alert-warning" >
            <button type= "button" class= "close" data-dismiss= "alert" > &times; </button>
            {{ message }}

        </div>
        {% endfor %}
    </div>
    {% endblock %}
{#    #}
{#    {% block inner_body %}#}
{##}
{#    {% block page_content %}{% endblock %}#}
{##}
{#    {% endblock %}#}


    {% block footer %}
    {% endblock %}


    {% block scripts %}
    {{ moment.include_moment() }}
    <script src="{{ url_for('static', filename = 'bower_components/bootstrap/dist/js/bootstrap.js') }}"></script>
    <script src="{{ url_for('static', filename = 'bower_components/jquery/dist/jquery.min.js') }}"></script>

    {% endblock %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{#{% block stylesheet %}#}
{#    {{ super() }}#}
{#{% endblock %}#}

{% block content %}
    Hello
    {% if not session.name  %}
        <a href="{{ url_for('main.user')}}">Click Link</a>
        {{ session }}

    {% else %}
        {{ session.name }}
    {% endif %}
    <p>
        The local date and time is {{ moment(current_time).format('LLL') }}.
    </p>
    <p>
        That was {{ moment(current_time).fromNow(refresh=True) }}
    </p>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/test.html
{% extends "base.html" %}

{%  block header %}
    <div class="page-header">
        <h1>Adam to do list!</h1>
    </div>
{%  endblock %}

{%  block content %}
    <div class="container">
    <div class="panel">
        <div class="input-group">
            <input class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default">Add</button>
            </span>
        </div>
        <table class="table-striped table">

            <thead>
                <tr>
                <th>Description</th>
                <th>Done</th>
            </tr>
            </thead>

            <tbody>
                <tr><td>Buy Flower</td><td>No</td></tr>
                <tr><td>Buy Game</td><td>Yes</td></tr>
                <tr><td>Buy Flower</td><td>No</td></tr>
                <tr><td>Buy Flower</td><td>No</td></tr>

            </tbody>
        </table>
    </div>
    </div>
{% endblock %}

app/templates/todo.html
{% extends "base.html" %}
{% block html %}
<html ng-app="todoApp">
{%  endblock %}


{%  block script_top %}


    <script src="{{ url_for('static',filename='bower_components/custom/custom.js') }}">
    </script>


{% endblock %}


{% block body %}
<body ng-controller="todoCtrl">
{% endblock %}

{%  block header %}
    <div class="page-header">
        {% raw %}
        <h1 align="center">{{todo.user}} To do List &af;
            <span class="label-default label" ng-hide="incompleteCount()==0" ng-class="warningLevel()">
            {{ incompleteCount() }}
            </span>
        </h1>

        {%  endraw %}
    </div>
{%  endblock %}

{%  block content %}
    <div class="container">
    <div class="panel">
        <div class="input-group">
            <input class="form-control" ng-model="actionText">
            <span class="input-group-btn">
                <button class="btn btn-default" ng-click="addnewItem(actionText)">Add</button>
            </span>
        </div>

        <table class="table-striped table">

            <thead>
                <tr>
                <th>Description</th>
                <th>Done</th>
            </tr>
            </thead>

            <tbody>
                  {%  raw %}
                  <tr ng-repeat='item in todo.items | visibleItems:visibleCompleted | orderBy:"action"'>
                        <td>{{ item.action }}</td>
                        <td><input type="checkbox" ng-model="item.done"></td>
                        <td>{{ item.done }}</td>
                  </tr>
                  {% endraw %}

            </tbody>
        </table>
        <hr>
        <div class="checkbox-inline">
            <label><input type="checkbox" ng-model="showCompleted">show Completed</label>
        </div>

        <div class="checkbox-inline">
            <label><input type="checkbox" ng-model="visibleCompleted">Hide unCompleted</label>
        </div>
    </div>
    </div>

{% endblock %}

app/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block stylesheet %}
    {{ super() }}
{% endblock %}
{% block content %}


<div class="container-fluid">
<div class="page-header">
	<form method="POST" action="">
        {{ form.name.label }} : {{ form.name(id='my-text-field') }}
        {% for mes in get_flashed_messages() %}
            <p style="color: red">{{ mes }}</p>
        {% endfor %}
        {{ form.submit() }}

{#        {{ wtf.quick_form(form) }}#}

	</form>
</div>
</div>

{% endblock %}


{% block scripts %}
    {{ super() }}
{% endblock %}